import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check, Globe2, Heart, Leaf, Handshake, Factory, Users, Package, Ship } from 'lucide-react';
import Container from '@/components/common/Container';

export const metadata: Metadata = { title: 'About Us | Bhavita Textiles', description: 'Indian roots. Global reach. A trusted wholesale partner in home textiles.' };
const images = { hero: 'https://bhavitatextiles.lovable.app/assets/product-mink-blankets-Cd-j1YKi.jpg', story: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=85', custom: 'https://bhavitatextiles.lovable.app/assets/product-bedsheet-styled-B1ras_mT.jpg' };
const values = [[Leaf, 'QUALITY IN EVERYTHING WE DO'], [Users, 'LOYAL PARTNERSHIPS'], [Heart, 'ETHICAL PRACTICES'], [Handshake, 'RESPECTING TRADITION'], [Globe2, 'A SUSTAINABLE TOMORROW']] as const;
const stats = [['10+', 'YEARS OF EXPERIENCE'], ['500+', 'SATISFIED BUSINESS CLIENTS'], ['1000+', 'PRODUCT VARIANTS'], ['PAN INDIA', 'SUPPLY NETWORK'], ['25+', 'COUNTRIES SERVED']] as const;

export default function AboutPage() { return <main data-testid="about-page" className="bg-bg text-ink">
  <section data-testid="about-hero" className="relative min-h-[520px] overflow-hidden"><Image src={images.hero} alt="Bhavita Textiles home textiles" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-bg via-bg/90 to-transparent" /><Container className="relative z-10 flex min-h-[520px] items-center py-20"><div className="max-w-xl"><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-brand">ABOUT US</p><h1 className="mt-5 font-serif text-5xl leading-[.98] sm:text-6xl">A Legacy Woven<br />Into Every Thread</h1><p className="mt-5 font-serif text-2xl text-ink-2">Indian roots. Global reach. A trusted wholesale partner in home textiles.</p><p className="mt-6 text-[15px] leading-7 text-ink-2">At Bhavita Textiles, we bring together the richness of Indian heritage and modern manufacturing to create premium home textiles for businesses across the world. With a passion for quality, craftsmanship, and long-term partnerships, we are committed to making beautiful homes possible — at scale.</p><Link href="/about#story" className="mt-7 inline-flex items-center gap-3 bg-brand px-6 py-3 text-[10px] font-semibold uppercase text-brand-ink">Our journey <ArrowRight size={15} /></Link></div></Container></section>
  <section id="story" data-testid="about-story" className="grid lg:grid-cols-[42%_58%]"><div className="relative min-h-[320px]"><Image src={images.story} alt="Our story and textile craft" fill sizes="42vw" className="object-cover" /><div className="absolute inset-0 bg-ink/40" /><div className="absolute inset-0 flex items-center justify-center text-center text-bg"><div><h2 className="font-serif text-5xl">Our<br />Story</h2><span className="mt-4 block text-gold">— ✦ —</span><p className="mt-4 font-serif text-xl">From tradition<br />to tomorrow.</p></div></div></div><div className="flex items-center p-10 lg:p-16"><div className="max-w-xl text-sm leading-6 text-ink-2"><p>Bhavita Textiles was founded with a simple belief — Indian craftsmanship deserves a global stage. What started as a family-driven passion for textiles has grown into a trusted wholesale brand serving clients across India and international markets.</p><p className="mt-5">With years of experience in textile manufacturing and sourcing, we combine traditional artistry with modern processes to deliver consistent quality, customised solutions, and reliable supply — for businesses of every size.</p></div></div></section>
  <section data-testid="about-stats" className="border-y border-border bg-surface"><Container className="grid grid-cols-2 sm:grid-cols-[repeat(5,1fr)_1.35fr]">{stats.map(([value, label]) => <div key={value} className="border-r border-border px-4 py-8 text-center last:border-0"><strong className="font-serif text-3xl">{value}</strong><span className="mt-2 block text-[10px] font-semibold uppercase tracking-wider2 text-ink-2">{label}</span></div>)}<div className="flex min-h-28 items-center justify-center bg-dark-green px-6 py-5 text-center text-bg sm:min-h-0"><p className="font-serif text-lg uppercase tracking-[.12em] text-gold">Trusted by businesses.<br />Crafted for tomorrow.</p></div></Container></section>
  <section data-testid="about-what-we-do" className="py-16"><Container className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><h2 className="font-serif text-4xl">What We Do</h2><span className="mt-5 block h-px w-14 bg-brand" /><p className="mt-5 max-w-md text-sm leading-6 text-ink-2">We manufacture and supply a wide range of home textiles including bed linen, blankets, towels, curtains, rugs, home décor, handloom collections, and handicrafts — designed to meet the needs of hotels, resorts, hospitals, retail stores, interior designers and more.</p><Link href="/shop" className="mt-6 inline-flex bg-brand px-6 py-3 text-[10px] font-semibold uppercase text-brand-ink">View our collection →</Link></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[['PREMIUM QUALITY', images.hero], ['WIDE RANGE', images.story], ['CUSTOM SOLUTIONS', images.custom], ['RELIABLE SUPPLY', images.hero]].map(([label, image]) => <div key={label} className="relative aspect-[.75] overflow-hidden"><Image src={image} alt={label} fill sizes="20vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-ink/85 to-transparent" /><span className="absolute bottom-5 left-2 right-2 text-center text-[10px] font-semibold text-bg">{label}</span></div>)}</div></Container></section>
  <section data-testid="about-values" className="bg-surface-2 py-14"><Container><h2 className="font-serif text-4xl">Our Values</h2><div className="mt-8 grid grid-cols-2 gap-6 sm:grid-cols-5">{values.map(([Icon, label]) => <div key={label} className="text-center"><Icon className="mx-auto size-8 text-brand" strokeWidth={1.3} /><p className="mt-4 text-[10px] font-semibold leading-4">{label}</p></div>)}</div></Container></section>
  <section data-testid="about-strength" className="grid lg:grid-cols-2"><div className="relative min-h-[350px]"><Image src={images.custom} alt="Crafted by people, inspired by heritage" fill sizes="50vw" className="object-cover" /></div><div className="grid sm:grid-cols-2"><div className="p-10"><h2 className="font-serif text-3xl">Our Manufacturing Strength</h2><p className="mt-4 text-sm leading-6 text-ink-2">Our state-of-the-art facilities and skilled artisans enable us to produce high-quality textiles with precision, scalability, and flexibility.</p><ul className="mt-5 space-y-2 text-xs text-ink-2">{['In-house & partner manufacturing units', 'Skilled artisans & experienced workforce', 'Customisation in designs, sizes, fabrics & packaging', 'Strict quality control at every stage', 'Large-scale production with timely delivery'].map((item) => <li key={item} className="flex gap-2"><Check className="size-4 shrink-0 text-brand" />{item}</li>)}</ul></div><div className="border-l border-border p-10"><Leaf className="size-9 text-brand" /><h2 className="mt-5 font-serif text-3xl">Sustainable Future</h2><p className="mt-4 text-sm leading-6 text-ink-2">We are committed to responsible manufacturing by promoting eco-friendly materials, ethical sourcing, and sustainable practices.</p><Link href="/about#values" className="mt-6 inline-flex bg-brand px-5 py-3 text-[10px] font-semibold uppercase text-brand-ink">Our sustainability →</Link></div></div></section>
  <section data-testid="about-global" className="py-14"><Container className="grid gap-8 lg:grid-cols-[1fr_1.4fr_.7fr] lg:items-center"><div><Globe2 className="size-9 text-brand" /><h2 className="mt-4 font-serif text-3xl">Our Global Presence</h2><p className="mt-4 max-w-lg text-sm leading-6 text-ink-2">From India to the world, our textiles are trusted by businesses in diverse industries. We continue to expand our reach, building long-term relationships through quality, reliability, and service excellence.</p></div><div className="flex min-h-48 items-center justify-center border-y border-border bg-[radial-gradient(circle_at_center,rgba(173,130,71,.22)_1px,transparent_1px)] bg-[length:18px_18px] text-center"><Globe2 className="size-28 text-gold/40" strokeWidth={.7} /></div><div className="border-l border-border pl-7 text-right"><p className="font-serif text-xl uppercase tracking-[.12em] text-brand">Indian textiles<br />for a brighter,<br />more beautiful tomorrow.</p></div></Container></section>
  <section data-testid="about-cta" className="bg-ink py-14 text-bg"><Container className="text-center"><h2 className="font-serif text-4xl">Let&apos;s Build Something Beautiful Together</h2><p className="mt-3 text-sm text-bg/75">Partner with Bhavita Textiles for reliable supply, customised solutions, and long-term growth.</p><div className="mt-7 flex justify-center gap-3"><Link href="/wholesale" className="bg-brand px-6 py-3 text-[10px] font-semibold uppercase text-brand-ink">Get wholesale quote →</Link><Link href="/contact" className="border border-bg/40 px-6 py-3 text-[10px] font-semibold uppercase">↓ Download catalogue</Link></div></Container></section>
</main>; }
