import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Check, Factory, PackageCheck, ShieldCheck, Truck } from 'lucide-react';
import { whatsappUrl } from '@/components/layout/WhatsAppWidget';

export const metadata: Metadata = { title: 'Eight years of loom-woven trust, shipped in bulk', description: 'Bhavita Textiles is a family-run manufacturer of printed bedsheets, mink blankets and floor mats for hospitality, export and corporate gifting buyers.' };

const images = {
  hero: 'https://bhavitatextiles.lovable.app/assets/hero-loom-factory-yO9x27s4.jpg',
  bedsheets: 'https://bhavitatextiles.lovable.app/assets/product-bedsheet-styled-B1ras_mT.jpg',
  blankets: 'https://bhavitatextiles.lovable.app/assets/product-mink-blankets-Cd-j1YKi.jpg',
  mats: 'https://bhavitatextiles.lovable.app/assets/product-floor-mats-D-ey-gLp.jpg',
  factory: 'https://bhavitatextiles.lovable.app/assets/factory-packaging-uSpSkn1N.jpg',
};



import ProductImageFallback from '@/components/common/ProductImageFallback';  

const range = [
    { slug: 'printed-double-bedsheets', href: '/shop/printed-bedsheets', title: 'Printed Double Bedsheets', label: 'Bestseller', copy: '100% cotton & poly-cotton, 144 TC / 180 TC / 210 TC, reactive-print, colour-fast.', bullets: ['Sizes 90x100 / 100x108 in', 'MOQ 500 pcs / design', 'Custom prints'], image: images.bedsheets },
  { slug: 'mink-blankets', href: '/shop/winter-blankets', title: 'Mink Blankets', label: 'Winter Line', copy: 'Double-ply mink & korean-mink blankets in premium GSM. Embossed and printed.', bullets: ['1.6 – 2.2 kg GSM', 'Single / Double sizes', 'Retail-ready packing'], image: images.blankets },
  { slug: 'floor-mats-dhurries', href: '/shop/cotton-door-mats', title: 'Floor Mats & Dhurries', label: 'Craft Range', copy: 'Handloom cotton dhurries and durable floor mats, block-print and pit-loom weaves.', bullets: ['Sizes 2x3 – 6x9 ft', 'MOQ 300 pcs', 'Vegetable dyes on request'], image: images.mats },
];

export default function HomePage() {
  return <div data-testid="home-page" className="overflow-hidden">
    <section data-testid="hero-section" className="grain relative min-h-[680px] bg-ink text-bg lg:min-h-[calc(100vh-88px)]">
      <Image src={images.hero} alt="Bhavita Textiles power-loom manufacturing floor in Panipat" fill priority sizes="100vw" className="object-cover opacity-60" />
      <div className="absolute inset-0 bg-gradient-to-r from-ink via-ink/70 to-ink/15" />
      <div className="relative z-10 mx-auto flex min-h-[680px] max-w-[1440px] items-center px-6 py-24 sm:px-10 lg:min-h-[calc(100vh-88px)] lg:px-16"><div className="max-w-3xl">
        <p data-testid="hero-eyebrow" className="text-[11px] font-bold uppercase tracking-[0.24em] text-gold">Panipat · India&apos;s Home-Textile Capital</p>
        <h1 data-testid="hero-heading" className="text-balance mt-6 font-serif text-6xl leading-[.9] sm:text-7xl lg:text-[7.6rem]">Eight years of loom-woven trust, shipped in bulk.</h1>
        <p data-testid="hero-description" className="mt-8 max-w-xl text-sm leading-7 text-bg/75 sm:text-base">Bhavita Textiles is a family-run manufacturer of printed bedsheets, mink blankets and floor mats — built for hospitality chains, export houses and corporate gifting programs that need consistent quality at plant scale.</p>
        <div className="mt-9 flex flex-wrap gap-3"><Link href="/products" data-testid="hero-catalogue-link" className="group inline-flex items-center gap-3 rounded-full bg-gold px-6 py-3.5 text-[11px] font-bold uppercase tracking-[0.16em] text-ink transition-transform hover:-translate-y-1">View Full Catalogue <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></Link><Link href="/wholesale" data-testid="hero-quote-link" className="inline-flex items-center rounded-full border border-bg/40 px-6 py-3.5 text-[11px] font-bold uppercase tracking-[0.16em] transition-colors hover:border-gold hover:text-gold">Request Bulk Quote</Link></div>
      </div></div>
      <div className="absolute bottom-0 left-0 right-0 z-10 border-t border-bg/20"><div className="mx-auto flex max-w-[1440px] flex-wrap gap-x-10 gap-y-3 px-6 py-5 text-[10px] font-semibold uppercase tracking-[0.16em] text-bg/65 sm:px-10 lg:px-16"><span data-testid="hero-stat-years">8+ Years in Panipat</span><span data-testid="hero-stat-skus">30+ Active SKUs</span><span data-testid="hero-stat-capacity">50K Units / month</span><span data-testid="hero-stat-markets">12+ Export markets</span></div></div>
    </section>

    <section data-testid="featured-range" className="bg-bg py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-6 sm:px-10 lg:px-16"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-2">Featured Range</p><h2 data-testid="featured-heading" className="mt-4 max-w-2xl text-balance font-serif text-5xl leading-[.95] sm:text-6xl">Categories our buyers reorder every season.</h2></div><p className="max-w-sm text-sm leading-7 text-ink-2">A curated look at three of our seven categories. Full technical specifications, GSM options and MOQ tiers are in the catalogue.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{range.map((item, index) => <Link href={item.href} key={item.slug} data-testid={`product-category-card-${index + 1}`} className="group border border-border bg-surface transition-transform hover:-translate-y-1"><div className="relative aspect-[1.15] overflow-hidden bg-surface-2"><ProductImageFallback slug={item.slug} remote={item.image} alt={item.title} /><div className="absolute left-5 top-5 bg-bg px-3 py-2 text-[10px] font-bold uppercase tracking-[0.16em] text-ink">{item.label}</div></div><div className="p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-gold-2">0{index + 1} · Category</p><h3 data-testid={`product-category-title-${index + 1}`} className="mt-3 font-serif text-3xl">{item.title}</h3><p className="mt-4 min-h-[54px] text-sm leading-6 text-ink-2">{item.copy}</p><ul className="mt-6 grid gap-2 text-xs text-ink-2">{item.bullets.map((bullet) => <li key={bullet} className="flex items-center gap-2"><Check size={13} className="text-gold-2" />{bullet}</li>)}</ul><span className="mt-7 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-ink">Explore range <ArrowUpRight size={14} className="transition-transform group-hover:translate-x-1" /></span></div></Link>)}</div><Link href="/products" data-testid="browse-all-categories-link" className="mt-10 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-ink transition-colors hover:text-gold-2">Browse all 7 categories <ArrowUpRight size={15} /></Link></div></section>
    <section data-testid="plant-scale-section" className="bg-surface-2 py-24 sm:py-32"><div className="mx-auto grid max-w-[1440px] gap-12 px-6 sm:px-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-16"><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-2">Plant Scale</p><h2 className="mt-4 text-balance font-serif text-5xl leading-[.95] sm:text-6xl">A working mill you can walk through — not a directory listing.</h2><p className="mt-7 max-w-lg text-sm leading-7 text-ink-2">Our 40,000 sq.ft. facility in Panipat runs power-looms, stitching, digital & rotary printing, and packaging under one roof. Every order you place is one shift on our floor — not a resold job order.</p><div className="mt-10 grid grid-cols-2 gap-7 border-t border-border pt-7 sm:grid-cols-4"><div><strong data-testid="plant-area-stat" className="font-serif text-3xl">40,000</strong><span className="mt-1 block text-[10px] uppercase tracking-wider2 text-ink-2">sq. ft. floor</span></div><div><strong data-testid="plant-team-stat" className="font-serif text-3xl">120+</strong><span className="mt-1 block text-[10px] uppercase tracking-wider2 text-ink-2">team members</span></div><div><strong className="font-serif text-3xl">5-stage</strong><span className="mt-1 block text-[10px] uppercase tracking-wider2 text-ink-2">inspection</span></div><div><strong className="font-serif text-3xl">&lt; 21</strong><span className="mt-1 block text-[10px] uppercase tracking-wider2 text-ink-2">days lead time</span></div></div></div><div className="relative aspect-[1.3] overflow-hidden"><Image src={images.factory} alt="Bhavita Textiles packaging zone" fill sizes="(min-width: 1024px) 55vw, 100vw" className="object-cover" /><span data-testid="factory-image-caption" className="absolute bottom-5 left-5 bg-bg px-3 py-2 text-[10px] font-bold uppercase tracking-[0.16em]">Live packaging zone</span></div></div></section>

    <section data-testid="why-bhavita-section" className="bg-bg py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-6 sm:px-10 lg:px-16"><div className="max-w-xl"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-2">Why Bhavita</p><h2 className="mt-4 text-balance font-serif text-5xl leading-[.95] sm:text-6xl">Built for procurement teams that hate surprises.</h2></div><div className="mt-14 grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-4">{[[Factory, 'Direct from the loom', 'No middlemen, no directory markups. You buy factory-priced, factory-quality.'], [ShieldCheck, 'Export-buyer ready', 'Pre-shipment inspection reports, spec sheets, GSM & shrinkage tests on request.'], [PackageCheck, 'Private label, easy', 'Custom prints, packaging, hangtags and cartons for retail and gifting programs.'], [Truck, 'Global logistics', 'FOB Nhava Sheva / Mundra. Consolidation for LCL orders across categories.']].map(([Icon, title, copy]) => <div key={title as string} className="bg-bg p-7 sm:p-9"><Icon className="text-gold-2" size={23} /><h3 className="mt-7 font-serif text-2xl">{title as string}</h3><p className="mt-3 text-sm leading-6 text-ink-2">{copy as string}</p></div>)}</div></div></section>

    <section data-testid="wholesale-cta" className="bg-ink py-24 text-bg sm:py-32"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-10 px-6 sm:px-10 md:flex-row md:items-end lg:px-16"><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold">Talk to the mill</p><h2 className="mt-4 max-w-2xl text-balance font-serif text-5xl leading-[.95] sm:text-6xl">Share your sizes, GSM and volume — get a factory quote within 24 hours.</h2></div><div className="flex shrink-0 flex-wrap gap-3"><Link href="/wholesale" data-testid="cta-rfq-link" className="inline-flex items-center gap-3 rounded-full bg-gold px-6 py-3.5 text-[11px] font-bold uppercase tracking-[0.16em] text-ink transition-transform hover:-translate-y-1">Send RFQ <ArrowRight size={15} /></Link><Link href="/contact" data-testid="cta-contact-link" className="inline-flex items-center rounded-full border border-bg/30 px-6 py-3.5 text-[11px] font-bold uppercase tracking-[0.16em] transition-colors hover:border-gold hover:text-gold">Contact team</Link></div></div></section>
    
  </div>;
}