'use client';

import Image from 'next/image';
import Link from 'next/link';
import Container from '@/components/common/Container';

const MILESTONES = [['2018', 'A family-run mill', 'Eight years of Panipat manufacturing excellence.'], ['40,000', 'sq. ft. facility', 'Power-looms, stitching, printing and packaging under one roof.'], ['< 21 days', 'typical lead time', 'Consistent quality, from one shift on our floor to your warehouse.']];

export default function BrandStory() {
  return <section data-testid="brand-story" className="bg-surface-2 py-20 sm:py-28"><Container><div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-20"><div className="relative"><div className="relative aspect-[1.1] overflow-hidden rounded-2xl bg-navy"><Image src="/images/editorial/royal-collection.svg" alt="Bhavita Textiles manufacturing story" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover opacity-80" /><div className="absolute inset-0 bg-gradient-to-tr from-navy/60 to-transparent" /></div><div data-testid="brand-story-caption" className="absolute bottom-5 left-5 rounded-xl border border-bg/20 bg-navy/80 px-4 py-3 text-[10px] font-bold uppercase tracking-[0.16em] text-bg backdrop-blur-md">In-house loom & finishing</div></div><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-2">Plant Scale</p><h2 className="mt-4 max-w-xl font-serif text-5xl leading-[0.92] text-navy sm:text-6xl">A working mill you can walk through — not a directory listing.</h2><p className="mt-7 max-w-xl text-sm leading-7 text-ink-2">Our 40,000 sq.ft. facility in Panipat runs power-looms, stitching, digital & rotary printing, and packaging under one roof. Every order you place is one shift on our floor — not a resold job order.</p><Link href="/about" data-testid="brand-story-cta" className="mt-8 inline-flex items-center gap-2 rounded-full bg-navy px-6 py-3.5 text-[11px] font-bold uppercase tracking-[0.16em] text-bg transition-colors hover:bg-gold hover:text-ink">Meet the mill <span>↗</span></Link></div></div><ol data-testid="brand-story-timeline" className="mt-16 grid gap-px overflow-hidden rounded-2xl border border-border bg-border md:grid-cols-3">{MILESTONES.map(([value, title, body]) => <li key={value} className="bg-bg p-7 sm:p-9"><p className="font-serif text-4xl text-gold-2">{value}</p><h3 className="mt-3 text-xs font-bold uppercase tracking-[0.14em] text-navy">{title}</h3><p className="mt-3 text-sm leading-6 text-ink-2">{body}</p></li>)}</ol></Container></section>;
}