'use client';

import { CheckCircle2, Circle } from 'lucide-react';

interface ShippingMethod { id: string; label: string; eta: string; price: number }
const METHODS: ShippingMethod[] = [{ id: 'standard', label: 'Standard delivery', eta: '5–7 business days', price: 150 }, { id: 'express', label: 'Express delivery', eta: '2–3 business days', price: 350 }, { id: 'white-glove', label: 'White-glove installation', eta: '7–10 business days', price: 800 }];

export default function ShippingStep({ selected, onSelect }: { selected?: string; onSelect: (methodId: string, method: ShippingMethod) => void }) {
  return <section data-testid="checkout-shipping-step" className="rounded-xl border border-border bg-surface p-6"><p className="text-xs font-semibold uppercase tracking-wider2 text-gold">Step 2</p><h2 className="mt-2 font-serif text-3xl text-ink">Delivery method</h2><p className="mt-2 text-sm text-ink-2">Choose how you would like your pieces to arrive.</p><div className="mt-6 grid gap-3">{METHODS.map((method) => { const active = selected === method.id; return <button key={method.id} type="button" data-testid={`shipping-method-${method.id}`} aria-pressed={active} onClick={() => onSelect(method.id, method)} className={`flex items-center gap-4 rounded-xl border-2 p-5 text-left transition-all ${active ? 'border-gold bg-ink text-bg shadow-luxe' : 'border-border bg-bg text-ink hover:border-gold/60'}`}><span className="shrink-0">{active ? <CheckCircle2 data-testid={`shipping-selected-${method.id}`} className="size-5 text-gold" /> : <Circle className="size-5 text-ink-2" />}</span><span className="flex-1"><span className={`block font-serif text-lg ${active ? 'text-bg' : 'text-ink'}`}>{method.label}</span><span className={`mt-1 block text-xs uppercase tracking-wider2 ${active ? 'text-bg/70' : 'text-ink-2'}`}>{method.eta}</span></span><span className={`text-sm font-semibold ${active ? 'text-gold' : 'text-ink'}`}>₹{method.price.toLocaleString('en-IN')}</span>{active ? <span data-testid={`shipping-label-${method.id}`} className="rounded-full bg-gold px-2 py-1 text-[10px] font-bold uppercase tracking-wider2 text-ink">Selected</span> : null}</button>; })}</div></section>;
}