'use client';

import { CheckCircle2, Circle } from 'lucide-react';

interface ShippingMethod { id: string; label: string; eta: string; price: number }
const METHODS: ShippingMethod[] = [{ id: 'standard', label: 'Standard delivery', eta: '5–7 business days', price: 150 }, { id: 'express', label: 'Express delivery', eta: '2–3 business days', price: 350 }, { id: 'white-glove', label: 'White-glove installation', eta: '7–10 business days', price: 800 }];

export default function ShippingStep({ selected, onSelect }: { selected?: string; onSelect: (methodId: string, method: ShippingMethod) => void }) {
 return <section data-testid="checkout-shipping-step" className="rounded-lg border border-border bg-surface p-6 sm:p-8 lg:p-10"><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-brand">Step 2</p><h2 className="mt-3 font-serif text-3xl text-ink">Delivery method</h2><p className="mt-2 text-sm text-ink-2">Choose how you would like your pieces to arrive.</p><div className="mt-7 grid gap-3">{METHODS.map((method) => { const active = selected === method.id; return <button key={method.id} type="button" data-testid={`shipping-method-${method.id}`} aria-pressed={active} onClick={() => onSelect(method.id, method)} className={`flex min-h-24 items-center gap-4 rounded-lg border p-5 text-left transition-colors focus-visible:ring-2 focus-visible:ring-gold ${active ? 'border-brand bg-brand-soft' : 'border-border bg-bg hover:border-brand/50'}`}><span className="shrink-0">{active ? <CheckCircle2 data-testid={`shipping-selected-${method.id}`} className="size-5 text-brand" /> : <Circle className="size-5 text-ink-2" />}</span><span className="flex-1"><span className="block font-serif text-lg text-ink">{method.label}</span><span className="mt-1 block text-xs uppercase tracking-[.14em] text-ink-2">{method.eta}</span></span><span className="text-sm font-semibold text-ink">₹{method.price.toLocaleString('en-IN')}</span></button>; })}</div></section>;
}