'use client';

import type { ProductVariant } from '@/types/ProductVariant';

export default function VariantPicker({ variants, selected, onChange }: { variants: ProductVariant[]; selected?: ProductVariant; onChange: (variant?: ProductVariant) => void }) {
  const sizes = [...new Set(variants.map((variant) => variant.size).filter(Boolean))] as string[];
  const colors = [...new Set(variants.map((variant) => variant.color).filter(Boolean))] as string[];
  if (!variants.length) return null;
  return <div data-testid="product-variant-picker" className="space-y-6 border-y border-border py-6">{sizes.length ? <fieldset><legend className="mb-3 text-[10px] uppercase tracking-[0.2em] text-ink-2">Size</legend><div className="flex flex-wrap gap-5">{sizes.map((size) => { const active = selected?.size === size; const available = variants.some((variant) => variant.size === size && variant.stock > 0); return <button key={size} type="button" data-testid={`variant-size-${size}`} disabled={!available} onClick={() => onChange(variants.find((variant) => variant.size === size && variant.stock > 0))} className={`border-b py-2 text-sm ${active ? 'border-gold-2 text-gold-2' : 'border-border text-ink-2'} disabled:cursor-not-allowed disabled:opacity-35`}>{size}</button>; })}</div></fieldset> : null}{colors.length ? <fieldset><legend className="mb-3 text-[10px] uppercase tracking-[0.2em] text-ink-2">Colour</legend><div className="flex flex-wrap gap-5">{colors.map((color) => { const active = selected?.color === color; const available = variants.some((variant) => variant.color === color && variant.stock > 0); return <button key={color} type="button" data-testid={`variant-color-${color}`} disabled={!available} onClick={() => onChange(variants.find((variant) => variant.color === color && variant.stock > 0))} className={`border-b py-2 text-sm ${active ? 'border-gold-2 text-gold-2' : 'border-border text-ink-2'} disabled:cursor-not-allowed disabled:opacity-35`}>{color}</button>; })}</div></fieldset> : null}<p data-testid="variant-stock-message" className="text-xs text-ink-2">{selected ? selected.stock > 0 ? `${selected.stock} available` : 'Out of stock' : 'Choose an option to see availability'}</p></div>;
}