'use client';

import { useMemo, useState } from 'react';
import { ChevronRight, X } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Switch } from '@/components/ui/switch';
import { cn } from '@/lib/utils';
import type { Category } from '@/types/Category';
import type { ProductFlag } from '@/services/product.service';

export interface ShopFilters { category?: string; minPrice?: number; maxPrice?: number; color?: string; size?: string; inStock?: boolean; flag?: ProductFlag }
interface Props { categories: Category[]; activeCategorySlug?: string; filters: ShopFilters; facets: { colors: string[]; sizes: string[]; priceMin: number; priceMax: number }; onChange: (next: Partial<ShopFilters>) => void; onReset: () => void; className?: string; compact?: boolean }

const swatches: Record<string, string> = { Ivory: '#f2efe6', Charcoal: '#36383d', Indigo: '#2a3b8f', Saffron: '#e89b2d', Crimson: '#a11b2c', Sky: '#8ec1e5', Emerald: '#1f6b4e', Burgundy: '#6e1a2b', Pearl: '#efe9e0', Cocoa: '#5b3a29', Sand: '#d8c5a4', Sage: '#a3b49c', Natural: '#e7dcc7', Earth: '#7a5a3a', Rose: '#c77a7a', Mustard: '#c99a2a' };
function treeOf(categories: Category[]) { const map = new Map<number, Category & { children: Category[] }>(); categories.forEach((c) => map.set(c.id, { ...c, children: [] })); const roots: (Category & { children: Category[] })[] = []; map.forEach((node) => node.parentId && map.has(node.parentId) ? map.get(node.parentId)!.children.push(node) : roots.push(node)); return roots.sort((a, b) => a.sortOrder - b.sortOrder); }
function has(node: Category & { children?: Category[] }, slug: string): boolean { return node.slug === slug || (node.children ?? []).some((child) => has(child, slug)); }
function CategoryNode({ node, activeSlug, onSelect, depth = 0 }: { node: Category & { children?: Category[] }; activeSlug?: string; onSelect: (slug: string) => void; depth?: number }) { const children = node.children ?? []; const [open, setOpen] = useState(depth === 0 || Boolean(activeSlug && has(node, activeSlug))); const active = activeSlug === node.slug; return <li><div className="flex items-center">{children.length ? <button type="button" aria-expanded={open} aria-label={open ? `Collapse ${node.name}` : `Expand ${node.name}`} onClick={() => setOpen((value) => !value)} className="mr-2 inline-flex size-5 items-center justify-center text-ink-2 hover:text-ink"><ChevronRight className={cn('size-3.5 transition-transform duration-200', open && 'rotate-90')} /></button> : <span className="mr-2 size-5" />}<button type="button" data-testid={`filter-category-${node.slug}`} onClick={() => onSelect(node.slug)} className={cn('flex-1 py-2 text-left text-sm hover:text-gold-2', depth === 0 ? 'font-medium text-ink' : 'text-ink-2', active && 'text-gold-2')}>{node.name}</button></div>{children.length && open ? <ul className="ml-3 border-l border-border pl-3">{children.map((child) => <CategoryNode key={child.id} node={child} activeSlug={activeSlug} onSelect={onSelect} depth={depth + 1} />)}</ul> : null}</li>; }

export default function FilterSidebar({ categories, activeCategorySlug, filters, facets, onChange, onReset, className, compact = false }: Props) {
  const tree = useMemo(() => treeOf(categories), [categories]);
  const lo = facets.priceMin || 0; const hi = facets.priceMax || 0; const min = typeof filters.minPrice === 'number' ? filters.minPrice : lo; const max = typeof filters.maxPrice === 'number' ? filters.maxPrice : hi;
  const activeCount = [filters.category && !activeCategorySlug, typeof filters.minPrice === 'number', typeof filters.maxPrice === 'number', filters.color, filters.size, filters.inStock, filters.flag].filter(Boolean).length;
  return <aside data-testid="filter-sidebar" className={cn('text-sm', !compact && 'border-t border-border', className)}><div className="flex items-end justify-between border-b border-border py-5"><div><p className="text-[10px] uppercase tracking-[0.26em] text-gold-2">Refine your selection</p><h2 className="mt-2 font-serif text-2xl text-ink">Filters</h2></div><button type="button" data-testid="filter-reset" onClick={onReset} disabled={!activeCount} className="inline-flex items-center gap-1 text-[9px] uppercase tracking-[0.18em] text-ink-2 hover:text-ink disabled:opacity-30"><X size={12} />Clear{activeCount ? ` (${activeCount})` : ''}</button></div>
    <Accordion type="multiple" defaultValue={['category', 'price']} className="w-full">
      {tree.length ? <AccordionItem value="category" className="border-b border-border"><AccordionTrigger className="py-5 text-[10px] uppercase tracking-[0.22em] text-ink hover:no-underline">Category</AccordionTrigger><AccordionContent className="pb-5"><ul>{tree.map((node) => <CategoryNode key={node.id} node={node} activeSlug={activeCategorySlug ?? filters.category} onSelect={(slug) => onChange({ category: slug })} />)}</ul></AccordionContent></AccordionItem> : null}
      <AccordionItem value="price" className="border-b border-border"><AccordionTrigger className="py-5 text-[10px] uppercase tracking-[0.22em] text-ink hover:no-underline">Price range</AccordionTrigger><AccordionContent className="pb-6"><div className="grid grid-cols-2 gap-4"><label className="grid gap-2"><span className="text-[9px] uppercase tracking-[0.16em] text-ink-2">From</span><input type="number" data-testid="filter-price-min-input" value={min} min={lo} max={hi} onChange={(e) => onChange({ minPrice: Number(e.target.value) })} className="h-9 border-b border-border bg-transparent text-sm text-ink outline-none focus:border-gold-2" /></label><label className="grid gap-2"><span className="text-[9px] uppercase tracking-[0.16em] text-ink-2">To</span><input type="number" data-testid="filter-price-max-input" value={max} min={lo} max={hi} onChange={(e) => onChange({ maxPrice: Number(e.target.value) })} className="h-9 border-b border-border bg-transparent text-sm text-ink outline-none focus:border-gold-2" /></label></div><div className="mt-6 space-y-3"><input type="range" data-testid="filter-price-min" min={lo} max={hi} step={Math.max(50, Math.round((hi - lo) / 200))} value={min} onChange={(e) => onChange({ minPrice: Math.min(Number(e.target.value), max) })} className="h-1 w-full accent-[var(--gold-2)]" aria-label="Minimum price" /><input type="range" data-testid="filter-price-max" min={lo} max={hi} step={Math.max(50, Math.round((hi - lo) / 200))} value={max} onChange={(e) => onChange({ maxPrice: Math.max(Number(e.target.value), min) })} className="h-1 w-full accent-[var(--gold-2)]" aria-label="Maximum price" /><div className="flex justify-between text-[10px] text-ink-2"><span data-testid="price-min-label">₹{min.toLocaleString('en-IN')}</span><span data-testid="price-max-label">₹{max.toLocaleString('en-IN')}</span></div></div></AccordionContent></AccordionItem>
      {facets.colors.length ? <AccordionItem value="color" className="border-b border-border"><AccordionTrigger className="py-5 text-[10px] uppercase tracking-[0.22em] text-ink hover:no-underline">Colour{filters.color ? <span className="ml-2 text-gold-2">· 1</span> : null}</AccordionTrigger><AccordionContent className="pb-6"><div className="grid grid-cols-6 gap-3">{facets.colors.map((color) => { const active = filters.color === color; const value = swatches[color] ?? '#d6c5ad'; return <button key={color} type="button" data-testid={`filter-color-${color.toLowerCase().replace(/\s+/g, '-')}`} aria-label={color} aria-pressed={active} onClick={() => onChange({ color: active ? undefined : color })} className={cn('group relative flex size-8 items-center justify-center rounded-full border', active ? 'border-gold-2 ring-2 ring-gold-2/30 ring-offset-2 ring-offset-bg' : 'border-border hover:border-gold-2')}><span aria-hidden className="size-5 rounded-full border border-ink/10" style={{ background: value }} /></button>; })}</div>{filters.color ? <p className="mt-4 text-[11px] text-ink-2">Selected: <span className="text-ink">{filters.color}</span></p> : null}</AccordionContent></AccordionItem> : null}
      {facets.sizes.length ? <AccordionItem value="size" className="border-b border-border"><AccordionTrigger className="py-5 text-[10px] uppercase tracking-[0.22em] text-ink hover:no-underline">Size{filters.size ? <span className="ml-2 text-gold-2">· 1</span> : null}</AccordionTrigger><AccordionContent className="pb-6"><div className="flex flex-wrap gap-x-5 gap-y-3">{facets.sizes.map((size) => { const active = filters.size === size; return <button key={size} type="button" data-testid={`filter-size-${size.toLowerCase().replace(/\s+/g, '-')}`} aria-pressed={active} onClick={() => onChange({ size: active ? undefined : size })} className={cn('border-b py-1 text-[11px] uppercase tracking-[0.12em]', active ? 'border-gold-2 text-gold-2' : 'border-transparent text-ink-2 hover:border-border hover:text-ink')}>{size}</button>; })}</div></AccordionContent></AccordionItem> : null}
      <AccordionItem value="avail" className="border-b-0"><AccordionTrigger className="py-5 text-[10px] uppercase tracking-[0.22em] text-ink hover:no-underline">Availability</AccordionTrigger><AccordionContent className="pb-6"><div className="grid gap-4"><FilterToggle label="In stock only" testid="filter-in-stock" checked={!!filters.inStock} onToggle={(value) => onChange({ inStock: value || undefined })} /><FilterToggle label="New arrivals" testid="filter-flag-new" checked={filters.flag === 'new_arrival'} onToggle={(value) => onChange({ flag: value ? 'new_arrival' : undefined })} /><FilterToggle label="Best sellers" testid="filter-flag-best" checked={filters.flag === 'best_seller'} onToggle={(value) => onChange({ flag: value ? 'best_seller' : undefined })} /><FilterToggle label="Featured" testid="filter-flag-featured" checked={filters.flag === 'featured'} onToggle={(value) => onChange({ flag: value ? 'featured' : undefined })} /></div></AccordionContent></AccordionItem>
    </Accordion>
  </aside>;
}
function FilterToggle({ label, testid, checked, onToggle }: { label: string; testid: string; checked: boolean; onToggle: (value: boolean) => void }) { return <label className="flex items-center justify-between gap-3 text-sm text-ink-2"><span>{label}</span><Switch data-testid={testid} checked={checked} onCheckedChange={onToggle} /></label>; }