'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { SlidersHorizontal, X } from 'lucide-react';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import Container from '@/components/common/Container';
import Breadcrumbs, { type BreadcrumbItem } from '@/components/shop/Breadcrumbs';
import FilterSidebar, { type ShopFilters } from '@/components/shop/FilterSidebar';
import SortDropdown from '@/components/shop/SortDropdown';
import Pagination from '@/components/shop/Pagination';
import ProductGrid from '@/components/shop/ProductGrid';
import { useCategories } from '@/hooks/useCategories';
import { useProductFacets, useProducts } from '@/hooks/useProducts';
import type { ProductFlag, ProductSort } from '@/services/product.service';
import type { Category } from '@/types/Category';
import { cn } from '@/lib/utils';

const SORTS: ProductSort[] = ['new', 'price_asc', 'price_desc', 'best_sellers', 'rating'];
const FLAGS: ProductFlag[] = ['new_arrival', 'best_seller', 'featured'];
export interface ShopBrowserProps { title: string; eyebrow?: string; description?: string; breadcrumbs: BreadcrumbItem[]; lockedCategorySlug?: string; lockedQuery?: string; lockedFlag?: ProductFlag; initialFlag?: ProductFlag; disableCategoryTree?: boolean; limit?: number }

function parseFilters(sp: URLSearchParams): ShopFilters { const filters: ShopFilters = {}; const category = sp.get('category'); const min = sp.get('minPrice'); const max = sp.get('maxPrice'); const color = sp.get('color'); const size = sp.get('size'); const flag = sp.get('flag'); if (category) filters.category = category; if (min) filters.minPrice = Number(min); if (max) filters.maxPrice = Number(max); if (color) filters.color = color; if (size) filters.size = size; if (flag && FLAGS.includes(flag as ProductFlag)) filters.flag = flag as ProductFlag; if (sp.get('inStock') === 'true') filters.inStock = true; return filters; }
function serialize(filters: ShopFilters, sort: ProductSort, page: number, query?: string) { const sp = new URLSearchParams(); if (filters.category) sp.set('category', filters.category); if (typeof filters.minPrice === 'number') sp.set('minPrice', String(filters.minPrice)); if (typeof filters.maxPrice === 'number') sp.set('maxPrice', String(filters.maxPrice)); if (filters.color) sp.set('color', filters.color); if (filters.size) sp.set('size', filters.size); if (filters.inStock) sp.set('inStock', 'true'); if (filters.flag) sp.set('flag', filters.flag); if (sort !== 'new') sp.set('sort', sort); if (page > 1) sp.set('page', String(page)); if (query) sp.set('q', query); return sp.toString(); }

export default function ShopBrowser({ title, eyebrow, description, breadcrumbs, lockedCategorySlug, lockedQuery, lockedFlag, initialFlag, disableCategoryTree, limit = 12 }: ShopBrowserProps) {
  const router = useRouter(); const sp = useSearchParams();
  const [filters, setFilters] = useState<ShopFilters>(() => parseFilters(sp as unknown as URLSearchParams));
  const [sort, setSort] = useState<ProductSort>(() => { const value = sp.get('sort'); return value && SORTS.includes(value as ProductSort) ? value as ProductSort : 'new'; });
  const [page, setPage] = useState(Math.max(1, Number(sp.get('page') ?? 1))); const [drawerOpen, setDrawerOpen] = useState(false);
  useEffect(() => { if (initialFlag && !filters.flag) setFilters((current) => ({ ...current, flag: initialFlag })); }, [initialFlag, filters.flag]);
  const effectiveCategory = lockedCategorySlug ?? filters.category; const effectiveFlag = lockedFlag ?? filters.flag;
  const params = useMemo(() => ({ category: effectiveCategory, q: lockedQuery, minPrice: filters.minPrice, maxPrice: filters.maxPrice, color: filters.color, size: filters.size, inStock: filters.inStock, flag: effectiveFlag, sort, page, limit }), [effectiveCategory, lockedQuery, filters.minPrice, filters.maxPrice, filters.color, filters.size, filters.inStock, effectiveFlag, sort, page, limit]);
  const { data, isLoading, isError, refetch, isFetching } = useProducts(params); const facetsParams = useMemo(() => ({ category: effectiveCategory, q: lockedQuery, flag: lockedFlag }), [effectiveCategory, lockedQuery, lockedFlag]); const { data: facets } = useProductFacets(facetsParams); const { data: categories = [] as Category[] } = useCategories();
  const safeFacets = { colors: facets?.colors ?? [], sizes: facets?.sizes ?? [], priceMin: facets?.priceMin ?? 0, priceMax: facets?.priceMax ?? 0 };
  const sync = useCallback((next: ShopFilters, nextSort: ProductSort, nextPage: number) => { const query = serialize(next, nextSort, nextPage, sp.get('q') ?? undefined); const path = window.location.pathname; router.replace(query ? `${path}?${query}` : path, { scroll: false }); }, [router, sp]);
  useEffect(() => { sync(filters, sort, page); }, [filters, sort, page, sync]);
  useEffect(() => { setPage(1); }, [filters.category, filters.minPrice, filters.maxPrice, filters.color, filters.size, filters.inStock, filters.flag, sort]);
  const changeFilters = useCallback((next: Partial<ShopFilters>) => setFilters((current) => ({ ...current, ...next })), []); const reset = useCallback(() => { setFilters({}); setSort('new'); setPage(1); }, []);
  const items = data?.items ?? []; const total = data?.meta.total ?? 0; const totalPages = data?.meta.totalPages ?? 1;
  const activeChips = useMemo(() => { const chips: { key: string; label: string; clear: () => void }[] = []; if (filters.category && !lockedCategorySlug) { const category = categories.find((item) => item.slug === filters.category); chips.push({ key: 'category', label: category?.name ?? filters.category, clear: () => changeFilters({ category: undefined }) }); } if (filters.color) chips.push({ key: 'color', label: filters.color, clear: () => changeFilters({ color: undefined }) }); if (filters.size) chips.push({ key: 'size', label: `Size ${filters.size}`, clear: () => changeFilters({ size: undefined }) }); if (filters.flag && !lockedFlag) chips.push({ key: 'flag', label: filters.flag === 'new_arrival' ? 'New arrivals' : filters.flag === 'best_seller' ? 'Best sellers' : 'Featured', clear: () => changeFilters({ flag: undefined }) }); if (filters.inStock) chips.push({ key: 'stock', label: 'In stock', clear: () => changeFilters({ inStock: undefined }) }); if (typeof filters.minPrice === 'number' || typeof filters.maxPrice === 'number') chips.push({ key: 'price', label: `₹${(filters.minPrice ?? 0).toLocaleString('en-IN')} – ₹${(filters.maxPrice ?? safeFacets.priceMax).toLocaleString('en-IN')}`, clear: () => changeFilters({ minPrice: undefined, maxPrice: undefined }) }); return chips; }, [filters, categories, lockedCategorySlug, lockedFlag, safeFacets.priceMax, changeFilters]);
  const sidebar = <FilterSidebar categories={disableCategoryTree ? [] : categories} activeCategorySlug={lockedCategorySlug ?? filters.category} filters={filters} facets={safeFacets} onChange={changeFilters} onReset={reset} />;
  return <div data-testid="shop-browser" className="bg-bg"><Container className="py-8 sm:py-12 lg:py-16"><Breadcrumbs items={breadcrumbs} /><div className="mt-10 max-w-4xl"><p className="text-[10px] uppercase tracking-[0.28em] text-gold-2">{eyebrow ?? 'Collection'}</p><h1 data-testid="shop-page-title" className="mt-4 font-serif text-5xl leading-[0.92] tracking-[-0.035em] text-ink sm:text-7xl">{title}</h1>{description ? <p className="mt-6 max-w-2xl text-sm leading-7 text-ink-2">{description}</p> : null}</div>
    <div className="mt-14 border-y border-border py-3 lg:hidden"><div className="flex items-center justify-between gap-3"><Sheet open={drawerOpen} onOpenChange={setDrawerOpen}><SheetTrigger asChild><button type="button" data-testid="filter-drawer-trigger" className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.2em] text-ink"><SlidersHorizontal size={15} strokeWidth={1.4} />Refine{activeChips.length ? <span className="text-gold-2">· {activeChips.length}</span> : null}</button></SheetTrigger><SheetContent side="left" className="flex w-full max-w-md flex-col gap-0 bg-bg p-5 text-ink sm:p-8"><div className="flex-1 overflow-y-auto">{sidebar}</div><div className="mt-6 flex gap-4 border-t border-border pt-5"><button type="button" data-testid="filter-drawer-reset" onClick={reset} className="flex-1 border border-border py-3 text-[10px] uppercase tracking-[0.2em]">Reset</button><button type="button" data-testid="filter-drawer-apply" onClick={() => setDrawerOpen(false)} className="flex-[2] bg-ink py-3 text-[10px] uppercase tracking-[0.2em] text-bg">Show {total} pieces</button></div></SheetContent></Sheet><SortDropdown value={sort} onChange={setSort} /></div></div>
    <div className="mt-10 grid grid-cols-1 gap-14 lg:grid-cols-[250px_1fr] lg:gap-16"><div className="hidden lg:block"><div className="sticky top-28">{sidebar}</div></div><div><div className="hidden items-center justify-between border-b border-border pb-5 lg:flex"><p data-testid="results-count" className={cn('text-[11px] uppercase tracking-[0.16em] text-ink-2', isFetching && 'opacity-50')}>{isLoading ? 'Loading collection…' : total === 0 ? 'No results' : `Showing ${(page - 1) * limit + 1}–${Math.min(page * limit, total)} of ${total}`}</p><SortDropdown value={sort} onChange={setSort} /></div>{activeChips.length ? <div data-testid="active-filter-chips" className="flex flex-wrap gap-4 border-b border-border py-4">{activeChips.map((chip) => <button key={chip.key} type="button" onClick={chip.clear} className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.16em] text-gold-2 hover:text-ink">{chip.label}<X size={12} /></button>)}</div> : null}<ProductGrid items={items} loading={isLoading} skeletonCount={limit} emptyTitle={isError ? 'We couldn’t load these pieces' : lockedQuery ? `No matches for “${lockedQuery}”` : 'No pieces match your filters'} emptyDescription={isError ? 'Please retry — your atelier feed will reappear shortly.' : 'Try widening the price range or removing a colour / size to see more.'} emptyAction={isError ? { label: 'Retry', onClick: () => refetch() } : activeChips.length ? { label: 'Clear filters', onClick: reset } : undefined} /><Pagination page={page} totalPages={totalPages} onChange={setPage} /></div></div>
  </Container></div>;
}