'use client';

import Link from 'next/link';
import Container from '@/components/common/Container';
import CartLineItem from '@/components/cart/CartLineItem';
import CartSummary from '@/components/cart/CartSummary';
import CouponInput from '@/components/cart/CouponInput';
import { useCart, useRemoveCartItem, useUpdateCartItem } from '@/hooks/useCart';

export default function CartPage() { const { data: cart, isLoading, isError } = useCart(); const update = useUpdateCartItem(); const remove = useRemoveCartItem(); if (isLoading) return <main data-testid="cart-loading" className="min-h-[60vh] bg-bg" />; if (isError || !cart) return <main data-testid="cart-auth-required" className="min-h-[50vh] bg-bg px-6 py-24 text-center"><h1 className="font-serif text-4xl text-ink">Your private collection awaits</h1><p className="mt-3 text-ink-2">Sign in to keep pieces in your bag.</p></main>; return <main data-testid="cart-page" className="bg-bg"><Container className="py-16 sm:py-24"><p className="text-[10px] uppercase tracking-[0.28em] text-gold-2">Your bag</p><h1 className="mt-4 font-serif text-5xl leading-none tracking-[-0.035em] text-ink sm:text-6xl">Review your order</h1><p className="mt-5 max-w-xl text-sm leading-7 text-ink-2">A considered selection, prepared with care and ready for its next room.</p>{cart.items.length ? <div className="mt-14 grid gap-14 lg:grid-cols-[1fr_350px] lg:gap-20"><section><ul data-testid="cart-items-list" className="divide-y divide-border border-y border-border">{cart.items.map((item) => <li key={item.id}><CartLineItem item={item} onQuantity={(quantity) => update.mutate({ id: item.id, quantity })} onRemove={() => remove.mutate(item.id)} /></li>)}</ul><CouponInput /></section><CartSummary cart={cart} /></div> : <div data-testid="cart-empty-state" className="mt-14 border-y border-border px-6 py-20 text-center"><p className="font-serif text-4xl text-ink">Your bag is empty</p><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-ink-2">Begin with a woven layer that makes the room feel like yours.</p><Link data-testid="cart-empty-cta" href="/shop" className="mt-8 inline-flex h-12 items-center bg-ink px-7 text-[10px] uppercase tracking-[0.2em] text-bg hover:bg-gold-2">Explore the catalogue</Link></div>}</Container></main>; }